using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Recorder.Model
{
    public static class Constants
    {
        /* please add entries ALPHABETICALLY into the correct region */
        #region COMMON
        public const string ACTION_TYPE_ALT_CLICK = "ALT+Click";
        public const string ACTION_TYPE_CLICK = "Click";
        public const string ACTION_TYPE_RIGHT_CLICK = "RightClick";
        public const string ACTION_TYPE_KEYSTROKE = "Keystroke";
        public const string ACTION_TYPE_HOVER = "Hover";
        public const string ACTION_TYPE_VERIFY = "Verify";
        public const string ATTRIB_CHECKED = "checked";
        public const string ATTRIB_CLASS = "class";
        public const string ATTRIB_ID = "id";
        public const string ATTRIB_NAME = "name";
        public const string ATTRIB_TITLE = "title";
        public const string ATTRIB_TYPE = "type";
        public const string BROWSER_FF = "Firefox";
        public const string CONTROL_TYPE_UNSUPPORTED = "Control type of the interacted element is not supported.";
        public const string DELAY_DFLT_VAL = "0";
        public const string DESCRIPTOR_TYPE_ID = "Id";
        public const string DESCRIPTOR_TYPE_XPATH = "xpath";
        public const string DUPLICATE_CONTROLNAME = "Unable to save because control names are not unique.";
        public const string EXECUTE_DFLT_VAL = "True";
        public const string STATUS_ACTION_DETECTED = "Click detected...";
        public const string STATUS_ACTION_DETECTED_BUT_CONT = "Keystroke detected...";
        public const string STATUS_ALREADY_MAPPED = "Control has already been mapped (refer to the selected control). Please click another element in the browser.";
        public const string STATUS_ASSIGNING_VALUE = "Assigning value...";
        public const string STATUS_AUTOLOGIN = "[AUTO-LOGIN]";
        public const string STATUS_DEFAULT = "";
        public const string STATUS_ERROR = "[Error]";
        public const string STATUS_INFO = "[Info]";
        public const string STATUS_INITIALIZING_ASSIGNVALUE = "Switching to Assign Value mode...";
        public const string STATUS_INITIALIZING_DEFAULT = "Switching to default mode...";
        public const string STATUS_INITIALIZING_VERIFY = "Switching to Verify mode...";
        public const string STATUS_OK = "[OK]";
        public const string STATUS_PAUSED = "[Paused]";
        public const string STATUS_PERFORM_AUTOLOGIN = "Performing automatic login...";
        public const string STATUS_READY = "[Recording]";
        public const string STATUS_READY_TO_VERIFY = "[Verify]";
        public const string STATUS_READY_TO_ASSIGN_VALUE = "[AssignValue]";
        public const string STATUS_RESUMING_RECORDING = "Resuming recording...";
        public const string STATUS_SCREEN_SAVED = "Screen has been saved!";
        public const string STATUS_SUCCESSFULLY_MAPPED = "Control has been mapped!";
        public const string STATUS_STEP_ADDED = "Step added";
        public const string STATUS_STOPPING_RECORDING = "Stopping recording...";
        public const string STATUS_TEST_PLAYBACK_ONGOING = "Test playback ongoing...";
        public const string STATUS_UNEXPECTED_ALERT_DETECTED = "Unexpected dialog is blocking recording";
        public const string STATUS_VERIFYING = "Verifying...";
        public const string STATUS_VERIFY_NOT_SUPPORTED = "Control verification not yet supported";
        public const string STATUS_WAIT = "[Wait]";
        public const string STATUS_WAITING_FOR_USER_INPUT = "Waiting for user input...";
        public const string VERIFYTYPE_VERIFYCONTENT = "VerifyText/VerifyValue";
        public const string GETVALUETYPE_ASSIGNVALUE = "AssignValue";
        public const string GETVALUETYPE_ASSIGNPARTIALVALUE = "AssignPartialValue";
        #endregion

        #region COSTPOINT
        public const int CP_ANCESTOR_FORM_INDEX_QUERY = -2;
        public const string CP_CONTROL_CALENDAR = "Calendar";
        public const string CP_CONTROL_LOGIN = "Login";
        public const string CP_CONTROL_MAINMENU = "MainMenu";
        public const string CP_CONTROL_MAINTOOLBAR = "MainToolBar";
        public const string CP_CONTROL_REPORTMAINTOOLBAR = "ReportToolBar";
        public const string CP_CONTROL_MESSAGESAREA = "MessagesArea";
        public const string CP_CONTROL_NAVMENU = "NavMenu";
        public const string CP_CONTROL_SEARCHAPPRESULTLIST = "SearchAppResultList";
        public const string CP_CONTROL_TABLECONTEXTMENU = "TableContextMenu";
        public const string CP_CONTROL_UNKNOWN = "Unknown";
        public const string CP_CONTROL_TYPE_BUTTON = "Button";
        public const string CP_CONTROL_TYPE_CALENDAR = "Calendar";
        public const string CP_CONTROL_TYPE_CHECKBOX = "CheckBox";
        public const string CP_CONTROL_TYPE_COMBOBOX = "ComboBox";
        public const string CP_CONTROL_TYPE_FORM = "Form";
        public const string CP_CONTROL_TYPE_LINK = "Link";
        public const string CP_CONTROL_TYPE_RADIOBUTTON = "RadioButton";
        public const string CP_CONTROL_TYPE_TAB = "Tab";
        public const string CP_CONTROL_TYPE_TABLE = "Table";
        public const string CP_CONTROL_TYPE_MULTIPARTTABLE = "MultiPartTable";
        public const string CP_CONTROL_TYPE_TEXTAREA = "TextArea";
        public const string CP_CONTROL_TYPE_TEXTBOX = "TextBox";
        public const string CP_CONTROL_TYPE_UNKNOWN = "Unknown";
        public const string CP_CUSTOM_VALUE_LKP = "LKP";
        public const string CP_CUSTOM_VALUE_LOOKUP = "LOOKUP";
        public const string CP_KEYWORD_ASSIGNPARTIALVALUE = "AssignPartialValueToVariable";
        public const string CP_KEYWORD_ASSIGNVALUETOVARIABLE = "AssignValueToVariable";
        public const string CP_KEYWORD_CLICK = "Click";
        public const string CP_KEYWORD_CLICKBUTTON = "ClickButton";
        public const string CP_KEYWORD_CLICKCANCELDIALOG = "ClickCancelDialogWithMessage";
        public const string CP_KEYWORD_CLICKMESSAGESAREABUTTON = "ClickMessagesAreaButton";
        public const string CP_KEYWORD_CLICKOKDIALOG = "ClickOkDialogWithMessage";
        public const string CP_KEYWORD_CLICKTABLECELLBUTTONBYROWCOLUMN = "ClickTableCellButtonByRowColumn";
        public const string CP_KEYWORD_CLICKTABLECHECKBOX = "ClickTableCheckBox";
        public const string CP_KEYWORD_CLICKTABLEROWHEADER = "ClickTableRowHeader";
        public const string CP_KEYWORD_RIGHTCLICKTABLEROWHEADER = "RightClickTableRowHeader";
        public const string CP_KEYWORD_RIGHTCLICKCOLUMNHEADER = "RightClickColumnHeader";
        public const string CP_KEYWORD_CLICKTEXTBOXBUTTON = "ClickTextBoxButton";
        public const string CP_KEYWORD_CLICKTODAY = "ClickToday";
        public const string CP_KEYWORD_CLICKTOOLBARBUTTON = "ClickToolbarButton";
        public const string CP_KEYWORD_CLOSE = "Close";
        public const string CP_KEYWORD_GETPARTIALMESSAGE = "GetPartialMessage";
        public const string CP_KEYWORD_GETTABLEROWWITHCOLUMNVALUE = "GetTableRowWithColumnValue";
        public const string CP_KEYWORD_SELECT = "Select";
        public const string CP_KEYWORD_SELECTDATE = "SelectDate";
        public const string CP_KEYWORD_SELECTMENU = "SelectMenu";
        public const string CP_KEYWORD_SET = "Set";
        public const string CP_KEYWORD_SETTABLECELLVALUE = "SetTableCellValue";
        public const string CP_KEYWORD_VERIFYEXIST = "VerifyExist";
        public const string CP_KEYWORD_VERIFYEXISTS = "VerifyExists";
        public const string CP_KEYWORD_VERIFYMENU = "VerifyMenu";
        public const string CP_KEYWORD_VERIFYMESSAGEEXISTS = "VerifyMessageExists";
        public const string CP_KEYWORD_VERIFYREADONLY = "VerifyReadOnly";
        public const string CP_KEYWORD_VERIFYTABLECELLVALUE = "VerifyTableCellValue";
        public const string CP_KEYWORD_VERIFYTABLECELLREADONLY = "VerifyTableCellReadOnly";
        public const string CP_KEYWORD_VERIFYTABLECOLUMNHEADERS = "VerifyTableColumnHeaders";
        public const string CP_KEYWORD_VERIFYTABS = "VerifyTabs";
        public const string CP_KEYWORD_VERIFYTEXT = "VerifyText";
        public const string CP_KEYWORD_VERIFYTITLE = "VerifyTitle";
        public const string CP_KEYWORD_VERIFYTOOLBARBUTTON = "VerifyToolbarButton";
        public const string CP_KEYWORD_VERIFYVALUE = "VerifyValue";
        public const string CP_FUNCTION_LOGIN = "Login";
        public const string CP_SCREEN_CP7LOGIN = "CP7Login";
        public const string CP_SCREEN_DIALOG = "Dialog";
        public const string CP_SCREEN_FILEUPLOADMANAGER = "FileUploadManager";
        public const string CP_SCREEN_LOGIN = "Login";
        public const string CP_SCREEN_LOOKUP = "Lookup";
        public const string CP_SCREEN_MAIN = "CP7Main";
        public const string CP_SCREEN_PAGESETUP = "PageSetup";
        public const string CP_SCREEN_PRINTOPTIONS = "PrintOptions";
        public const string CP_SCREEN_PROCESSPROGRESS = "ProcessProgress";
        public const string CP_SCREEN_QUERY = "Query";
        public const string CP_SCREEN_SELECTCOMPANY = "SelectCompany";
        public const string CP_SCREEN_SUBMITBATCHJOB = "SubmitBatchJob";
        public const string CP_SCREEN_UNKNOWN = "Unknown";
        public const string CP_SCREEN_USERPREFERENCES = "UserPreferences";
        public const string CP_SCREEN_APPLICATIONVIEW = "ApplicationView";
        public const string CP_SCREEN_BROWSEFILEPOPUP = "BrowseFilePopup";
        public const string CP_SCREEN_REPORT = "Report";
        public const string CP_SCREEN_DATEPICKER = "DatePicker";
        #endregion
    }
}
