// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace METHConverter.Templates
{
    using CommonLib.DlkSystem;
    using CommonLib.DlkHandlers;
    using CommonLib.DlkRecords;
    using METHConverter.Utilities;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\TFS\QEAutomation\Selenium\BrowserFramework\Code\BrowserFramework\METHConverter\Templates\TestRunTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class TestRunTemplate : TestRunTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing Core.Sys;\r\nusing Core.Sys.Selenium;\r\nusing SeleniumCostpoint" +
                    ".Tests;\r\n\r\nnamespace SeleniumCostpoint.TestRuns\r\n{\r\n    public class ");
            
            #line 19 "C:\TFS\QEAutomation\Selenium\BrowserFramework\Code\BrowserFramework\METHConverter\Templates\TestRunTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TestRunName));
            
            #line default
            #line hidden
            this.Write(" : SeleniumTestRun\r\n    {\r\n        public ");
            
            #line 21 "C:\TFS\QEAutomation\Selenium\BrowserFramework\Code\BrowserFramework\METHConverter\Templates\TestRunTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TestRunName));
            
            #line default
            #line hidden
            this.Write("(Logger SessionLogger, String Environment) : base(SessionLogger, Environment) { }" +
                    "\r\n\r\n        public override void ExecuteTests()\r\n        {\r\n\t\t");
            
            #line 25 "C:\TFS\QEAutomation\Selenium\BrowserFramework\Code\BrowserFramework\METHConverter\Templates\TestRunTemplate.tt"

			foreach(TestInfo mTest in Tests)
			{
		
            
            #line default
            #line hidden
            this.Write("\t\tnew ");
            
            #line 29 "C:\TFS\QEAutomation\Selenium\BrowserFramework\Code\BrowserFramework\METHConverter\Templates\TestRunTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mTest.name.Trim().Replace(" ", "_")));
            
            #line default
            #line hidden
            this.Write("().Run(this,SeleniumDriver.Browser.");
            
            #line 29 "C:\TFS\QEAutomation\Selenium\BrowserFramework\Code\BrowserFramework\METHConverter\Templates\TestRunTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mTest.browser.ToString().ToUpper()));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 29 "C:\TFS\QEAutomation\Selenium\BrowserFramework\Code\BrowserFramework\METHConverter\Templates\TestRunTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mTest.environment));
            
            #line default
            #line hidden
            this.Write("\" );\r\n\t\t");
            
            #line 30 "C:\TFS\QEAutomation\Selenium\BrowserFramework\Code\BrowserFramework\METHConverter\Templates\TestRunTemplate.tt"

			}
		
            
            #line default
            #line hidden
            this.Write("           \r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
        
        #line 1 "C:\TFS\QEAutomation\Selenium\BrowserFramework\Code\BrowserFramework\METHConverter\Templates\TestRunTemplate.tt"

private string _TestRunNameField;

/// <summary>
/// Access the TestRunName parameter of the template.
/// </summary>
private string TestRunName
{
    get
    {
        return this._TestRunNameField;
    }
}

private global::System.Collections.Generic.List<TestInfo> _TestsField;

/// <summary>
/// Access the Tests parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<TestInfo> Tests
{
    get
    {
        return this._TestsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool TestRunNameValueAcquired = false;
if (this.Session.ContainsKey("TestRunName"))
{
    this._TestRunNameField = ((string)(this.Session["TestRunName"]));
    TestRunNameValueAcquired = true;
}
if ((TestRunNameValueAcquired == false))
{
    string parameterValue = this.Host.ResolveParameterValue("Property", "PropertyDirectiveProcessor", "TestRunName");
    if ((string.IsNullOrEmpty(parameterValue) == false))
    {
        global::System.ComponentModel.TypeConverter tc = global::System.ComponentModel.TypeDescriptor.GetConverter(typeof(string));
        if (((tc != null) 
                    && tc.CanConvertFrom(typeof(string))))
        {
            this._TestRunNameField = ((string)(tc.ConvertFrom(parameterValue)));
            TestRunNameValueAcquired = true;
        }
        else
        {
            this.Error("The type \'System.String\' of the parameter \'TestRunName\' did not match the type of" +
                    " the data passed to the template.");
        }
    }
}
if ((TestRunNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("TestRunName");
    if ((data != null))
    {
        this._TestRunNameField = ((string)(data));
    }
}
bool TestsValueAcquired = false;
if (this.Session.ContainsKey("Tests"))
{
    this._TestsField = ((global::System.Collections.Generic.List<TestInfo>)(this.Session["Tests"]));
    TestsValueAcquired = true;
}
if ((TestsValueAcquired == false))
{
    string parameterValue = this.Host.ResolveParameterValue("Property", "PropertyDirectiveProcessor", "Tests");
    if ((string.IsNullOrEmpty(parameterValue) == false))
    {
        global::System.ComponentModel.TypeConverter tc = global::System.ComponentModel.TypeDescriptor.GetConverter(typeof(global::System.Collections.Generic.List<TestInfo>));
        if (((tc != null) 
                    && tc.CanConvertFrom(typeof(string))))
        {
            this._TestsField = ((global::System.Collections.Generic.List<TestInfo>)(tc.ConvertFrom(parameterValue)));
            TestsValueAcquired = true;
        }
        else
        {
            this.Error("The type \'System.Collections.Generic.List<TestInfo>\' of the parameter \'Tests\' did" +
                    " not match the type of the data passed to the template.");
        }
    }
}
if ((TestsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Tests");
    if ((data != null))
    {
        this._TestsField = ((global::System.Collections.Generic.List<TestInfo>)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class TestRunTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
